name: AOSP Clang

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: zycromerz/kerneldocker:v3

    steps:
    - uses: actions/checkout@v3
    - name: Clang Cloning
      env:
        TOKEN_EMAIL: ${{ secrets.TOKEN_EMAIL }}
        TOKEN_USERNAME: ${{ secrets.TOKEN_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        TOKEN_PUSH_REPO_URL: ${{ secrets.TOKEN_PUSH_REPO_URL }}
      run: |
        bash clone